# ==========================================
# (NODES) GSMM ADAPTER
# ==========================================
model:
  is_a: named thing
  represented_as: node
  label_in_input: model

organism:
  is_a: named thing
  represented_as: node
  label_in_input: organism

compartment:
  is_a: cellular component
  represented_as: node
  label_in_input: compartment

model gene:
  is_a: gene
  represented_as: node
  label_in_input: model_gene

model reaction:
  is_a: molecular activity
  represented_as: node
  label_in_input: model_reaction

model metabolite:
  is_a: chemical entity
  represented_as: node
  label_in_input: model_metabolite

# ==========================================
# (EDGES) GSMM ADAPTER
# ==========================================
model has organism:
  is_a: related to
  represented_as: edge
  label_in_input: model_has_organism
  source: model
  target: organism

model has gene:
  is_a: related to
  represented_as: edge
  label_in_input: model_has_gene
  source: model
  target: model gene

model has reaction:
  is_a: related to
  represented_as: edge
  label_in_input: model_has_reaction
  source: model
  target: model reaction

model has metabolite:
  is_a: related to
  represented_as: edge
  label_in_input: model_has_metabolite
  source: model
  target: model metabolite

model has compartment:
  is_a: related to
  represented_as: edge
  label_in_input: model_has_compartment
  source: model
  target: compartment

gene reaction:
  is_a: related to
  represented_as: edge
  label_in_input: gene_reaction
  source: model gene
  target: model reaction

reaction metabolite:
  is_a: related to
  represented_as: edge
  label_in_input: reaction_metabolite
  source: model reaction
  target: model metabolite

metabolite in compartment:
  is_a: located in
  represented_as: edge
  label_in_input: metabolite_in_compartment
  source: model metabolite
  target: compartment

reaction in compartment:
  is_a: occurs in
  represented_as: edge
  label_in_input: reaction_in_compartment
  source: model reaction
  target: compartment

# ==========================================
# Layer 2: PUBMED
# ==========================================

pubmed_article:
  is_a: publication
  represented_as: node
  label_in_input: pubmed_article
  preferred_id: pmid
  properties:
    pmid: str
    title: str
    journal: str
    pub_date: str
    doi: str
    authors: str
    abstract: str
    url: str

biomedical_entity_has_literature:
  is_a: related to
  represented_as: edge
  label_in_input: biomedical_entity_has_literature
  properties:
    query: str
    score: int
    matched_on: str


entities:
  - alias: metabolite
    labels: ["ModelMetabolite"]
    id_property: "id"
    text_properties:
      - "name"
      - "id"

  - alias: gene
    labels: ["ModelGene"]
    id_property: "id"
    text_properties:
      - "name"
      - "id"

  - alias: reaction
    labels: ["ModelReaction"]
    id_property: "id"
    text_properties:
      - "name"
      - "id"

  - alias: compartment
    labels: ["Compartment"]
    id_property: "id"
    text_properties:
      - "name"
      - "id"

  - alias: publication
    labels: ["Publication"]
    id_property: "doi"
    text_properties:
      - "title"
      - "abstract"
  
  - alias: protein
    labels: ["Protein"]
    id_property: "id"
    text_properties:
      - "name"
      - "uniprot_id"
      - "generic_annotations"

  - alias: functional_term
    labels: ["FunctionalTerm"]
    id_property: "id"
    text_properties:
      - "category"
      - "description"

# ==========================================
# Layer 3: STRING DB (Proteins & Functions)
# ==========================================

protein:
  is_a: gene product
  represented_as: node
  label_in_input: protein
  preferred_id: id
  properties:
    name: str
    size: str
    annotation: str
    tax_id: str

functional_term:
  is_a: biological entity
  represented_as: node
  label_in_input: functional_term
  preferred_id: id
  properties:
    name: str
    category: str

encodes:
  is_a: related to
  represented_as: edge
  label_in_input: encodes
  source: model gene
  target: protein
  properties:
    source: str

has_functional_annotation:
  is_a: related to
  represented_as: edge
  label_in_input: has_functional_annotation
  source: protein
  target: functional_term

interacts_with:
  is_a: pairwise molecular interaction
  represented_as: edge
  label_in_input: interacts_with
  source: protein
  target: protein
  properties:
    neighborhood: int
    neighborhood_transferred: int
    fusion: int
    cooccurence: int
    homology: int
    coexpression: int
    coexpression_transferred: int
    experiments: int
    experiments_transferred: int
    database: int
    database_transferred: int
    textmining: int
    textmining_transferred: int
    combined_score: int